# Figure generation configuration for the example presentation.
# See shared/figure-config.yaml for the default template.
data folder: './../data/'
figures folder: './../pdf/'
figure size:
  x: 8.0
  y: 6.0
aspect ratio: 1.0
